apiVersion: batch/v1
kind: Job
metadata:
  name: "%NAME%"
spec:
  template:
    spec:
      containers:
      - name: benchmark
        image: "%IMAGE%"
        args: %ARGS%
        resources:
          requests:
            memory: "%MEMORY%"
        env:
        - name: FDB_DEBUG
          value: "1"
      restartPolicy: Never
      imagePullSecrets:
        - name: "%SECRET%"
      hostAliases: [{"ip": "10.97.3.1", "hostnames": ["infra1", "infra1.can.pt.horizon-opencube.eu"]}]
  ttlSecondsAfterFinished: 0
  backoffLimit: 1
