apiVersion: batch/v1
kind: Job
metadata:
  name: "%NAME%"
spec:
  template:
    spec:
      containers:
      - name: benchmark
        image: "%IMAGE%"
        resources:
          requests:
            memory: "%MEMORY%"
        env:
        - name: LD_LIBRARY_PATH
          value: /root/miniforge3/lib
        - name: PROJ_LIB
          value: /root/miniforge3/share/proj
      restartPolicy: Never
      imagePullSecrets:
        - name: "%SECRET%"
  ttlSecondsAfterFinished: 0
  backoffLimit: 1
